### ISSUE TITLE
Search result link for alert dialog is incorrect.

### ISSUE THREAD

**Issue by murdak** [reflex-dev/reflex-web#1001]
Search result for alert dialog: https://reflex.dev/docs/library/overlay/alertdialog/

Correct link: https://reflex.dev/docs/library/overlay/alert-dialog/

**Comment by Spartan-71** [comment]
This issue seems to be related with the **[inkeep](https://inkeep.com/)** and reflex integration for Documentation. 

How do I check the integration with inkeep, using the _apiKey_ and _integrationId_ mentioned in the **inkeep.py** file.

path: /pcweb/components/docpage/navbar/inkeep.py

**Comment by Spartan-71** [comment]
Hey @picklelo can u help me with the **inkeep** integration.

**Comment by dentro-innovation** [comment]
Same happens btw with https://reflex.dev/docs/library/datadisplay/spinner/ , also a broken link suggested by inkeep

**Comment by picklelo** [comment]
Are you guys still seeing this issue? We've updated the inkeep index now.

**Comment by Spartan-71** [comment]
@picklelo Nope, links for spinner and alert-dialog are working fine.
