### ISSUE TITLE
Issue with reflex.dev documentation

### ISSUE THREAD

**Issue by AdrianM10** [reflex-dev/reflex-web#1025]
Path: /docs/tutorial/frontend

The padding value shown in the docs  of "1em" for the action bar results in placeholder text being clipped and not clearly visible. 

```
# Styles for the action bar.
input_style = dict(
    border_width="1px",
    padding="1em",
    box_shadow=shadow,
    width="350px",
)
button_style = dict(
    background_color=rx.color("accent", 10),
    box_shadow=shadow,
)
```

See below screenshot:

![Screenshot 2024-10-12 at 06 31 20](https://github.com/user-attachments/assets/aab16f67-32d9-42ae-8783-1d585a6f04b1)

The padding value should be set to "0.5em" for the action bar input style. 

Below is a screenshot after changing the padding value to "0.5em"

![Screenshot 2024-10-12 at 06 33 42](https://github.com/user-attachments/assets/7436f1cc-5608-413e-905d-0ceae2587b52)

**Comment by Alek99** [comment]
Thanks for reporting will fix
