### ISSUE TITLE
Unable to Run Reflex-Web Locally Due to Multiple Errors

### ISSUE THREAD

**Issue by anxkhn** [reflex-dev/reflex-web#1053]
Description

I encountered multiple issues while attempting to set up and run the Reflex-Web project locally. Here is a detailed breakdown of the errors and steps taken:

1. Missing Logos: On the landing page, logos for Amazon, Google, and other brands were not being displayed on deployed website. The network tab indicated that the assets doesn't exist but are is present in source code assets folder.

2. Setup Challenges:

Windows: Attempted to set up on Windows, but the build failed due to an EMFILE error (too many open files).

Linux: Switched to a Linux environment (Pop!_OS 22.04) and followed the setup process. Now encountering additional issues related to component rendering and dependencies.

3. Deprecation Warnings and Errors:

Warnings:

DeprecationWarning: rx.chakra has been deprecated in version 0.6.0 and moved to a separate package. Install the "reflex-chakra" package via pip.

DeprecationWarning: Unannotated event handler arguments have been deprecated in version 0.6.3. Provide type annotations for event handler arguments.

Warning: rx._x contains experimental features and might be removed at any time in the future.

Runtime Error:

An AttributeError is raised during component rendering:

Error while rendering <class 'flexdown.blocks.eval_block.EvalBlock'> on line 13.
...
AttributeError: 'ExperimentalNamespace' object has no attribute 'code_block'

System Configuration

OS: Pop!_OS 22.04 LTS (Linux)

Python Version: 3.11

Steps to Reproduce

1. Clone the https://github.com/reflex-dev/reflex-web repository.

2. Follow the setup instructions on Linux.

3. Run the application.

Observed Behavior

Logos are missing on the landing page.

The build fails on Windows due to an EMFILE error.

On Linux, several deprecation warnings appear, and the app crashes with an AttributeError.

Expected Behavior

Successful local build and run of Reflex-Web without missing assets or critical errors.

Additional Context

I have a keen interest in debugging and contributing to this project, but these issues block further progress. Please advise on potential fixes or workarounds.

**Comment by ElijahAhianyo** [comment]
for the attribute errors, you actually need to run reflex-web with the current reflex pre-release `0.6.4a1`
