### ISSUE TITLE
add poetry

### ISSUE THREAD

**Issue by benedikt-bartscher** [reflex-dev/reflex-web#1057]
Prevent issues like https://github.com/reflex-dev/reflex-web/issues/1053

If you need a `requirements.txt` you can generate one with `poetry export --without-hashes --format=requirements.txt > requirements.txt`

**Comment by picklelo** [comment]
We don't want to use poetry for this package, since we want to be as general as possible. One thing we could do is pin the reflex version to the git version to make pinning the reflex version more consistent.
