### ISSUE TITLE
Site and docs not well indexed by Google etc

### ISSUE THREAD

**Issue by tedmiston** [reflex-dev/reflex-web#106]
Hey guys -

I was doing some searching on a project today trying to find an easy way to change the default config from being `chakra-ui-dark` to `chakra-ui-light`.  The search on the docs site wasn't too helpful, so I turned to web search engines.

[I was hoping to find something on `pc.App` that I could set like a `color_mode=light|dark|system`.  I know about the toggle color mode button, but I'm just looking for light mode or system mode by default without having that.]

When I did that, I noticed that Google has only indexed [3 pages][1] of the dozens of pages on the docs site.  I'm not sure if this issue is specific to the docs subdir; jumping up a level to the domain itself only adds [1 more page][2] (the homepage).  It seems there is no `robots.txt` file at <https://pynecone.io/robots.txt>; instead that returns a blank 404-ish page.

Do you know if the site has already been submitted to the [Google Search Console][3]?

I know from experience that SEO for Next.js apps can be non-trivial.  I also took a deeper look and saw that it looks like you're hosting on S3 with Cloudfront, so I suppose the site is a [static export][4].  If those assumptions are right, I think getting the site picked up by Googlebot ~~should~~ might "just work".

[1]: https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fpynecone.io%2Fdocs%2F
[2]: https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fpynecone.io
[3]: https://search.google.com/search-console
[4]: https://nextjs.org/docs/app/building-your-application/deploying/static-exports

**Comment by Alek99** [comment]
We have been working on some improvements to the SEO all the pages should be indexable now

**Comment by picklelo** [comment]
We are now indexed better by Google, though still many improvements to be made.
