### ISSUE TITLE
Some docs pages broken (throwing 404s) today

### ISSUE THREAD

**Issue by tedmiston** [reflex-dev/reflex-web#112]
Hey guys -

There's a weird issue with some docs pages throwing 404s today.

I was browsing the DataTable page yesterday and it was working just fine.

I notice the docs were changed recently by @ElijahAhianyo in https://github.com/pynecone-io/pcweb/pull/109, so maybe that deploy went out recently or I was looking at a cached working page yesterday.

Many of the pages are working from what I can tell, but several are throwing fresh 404s.  I don't see anything obviously wrong in that PR itself, so maybe just a bad build / deploy, or something borked in the Cloudfront distro?

For example: https://pynecone.io/docs/library/datadisplay/datatable

Screenshot:

<img width="1792" alt="Screen Shot 2023-06-22 at 12 46 53 PM" src="https://github.com/pynecone-io/pcweb/assets/366688/89e09a0b-68bf-49fa-be7f-a74955262b26">

Another broken page is https://pynecone.io/docs/library/datadisplay/codeblock

@picklelo can you try redeploying to see if that fixes it?

**Comment by picklelo** [comment]
@tedmiston Thanks for pointing this out - I just redeployed the website. Can you confirm if the pages are working for you now?

**Comment by tedmiston** [comment]
@picklelo confirmed.  thanks for the quick fix!

**Comment by tedmiston** [comment]
@picklelo it seems to be either happening again on different pages - https://pynecone.io/docs/library/typography/span

**Comment by picklelo** [comment]
@tedmiston That is strange thanks I'll try to figure out what's happening here...

**Comment by picklelo** [comment]
Just deployed again, went through a bunch of pages but let me know if there are still any missing ones.
