### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by iseletsk** [reflex-dev/reflex-web#171]
this page: [https://reflex.dev/docs/state/vars/](https://reflex.dev/docs/state/vars/ "https://reflex.dev/docs/state/vars/") In this section: Vars support many common operations. They can be used for arithemtic, string concatenation, inequalities, indexing, and more. See the full list of supported operations. The link from the full list of supported operations is broken.

**Comment by Alek99** [comment]
Thanks fixing now
