### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by DermeX21** [reflex-dev/reflex-web#385]
I can't run my code and I don't see my page, Although it appear this 
![Opera Instantánea_2024-01-21_112950_localhost](https://github.com/reflex-dev/reflex-web/assets/157284569/a3d9196f-fa2f-4537-9266-45d446d1cada)

**Comment by DermeX21** [comment]
I am using Windows 10 Home 22H2, Python 3.12 and Reflex 0.3.8. I have used python installed apart of visual studio and reflex. So far, everthing was working well.

**Comment by picklelo** [comment]
should be resolved in the latest main
