### ISSUE TITLE
The link for ‘Resource -> Contribute to Open Source“ is outdated

### ISSUE THREAD

**Issue by tankztz** [reflex-dev/reflex-web#403]
The event is October 2023, anything new we can provide?

https://github.com/reflex-dev/reflex-web/blob/577cef37ae54562544c1696eb9b7fb8c537dc525/pcweb/constants.py#L17

**Comment by Spartan-71** [comment]
@Lendemor this issue is already fixed.

checkout : [link](https://github.com/reflex-dev/reflex-web/commit/63822df324d3cd510f179cb749e4962ad81ce26c#diff-c0b22dd807453603006eb960193649541023a067ee7effc0d9cd96d51fb43fdeR17)
