### ISSUE TITLE
Multiple AttributeErrors when trying to run locally

### ISSUE THREAD

**Issue by Yummy-Yums** [reflex-dev/reflex-web#414]
I'm experiencing multiple AttributeErrors when trying to _reflex run_ locally. They are listed below

1)
Clear_modules( )
  _File "/home/eliasderby/Desktop/python/oss/reflex-web/reflex-web/pcweb/pcweb.py", line 9, in <module>
    from pcweb.pages import page404, routes
  File "/home/eliasderby/Desktop/python/oss/reflex-web/reflex-web/pcweb/pages/__init__.py", line 3, in <module>
    from .blog import blog_routes
  File "/home/eliasderby/Desktop/python/oss/reflex-web/reflex-web/pcweb/pages/blog.py", line 5, in <module>
    from pcweb.flexdown import xd
  File "/home/eliasderby/Desktop/python/oss/reflex-web/reflex-web/pcweb/flexdown.py", line 210, in <module>
    xd.clear_modules()
    ^^^^^^^^^^^^^^^^
**AttributeError: 'Flexdown' object has no attribute 'clear_modules'**

Simple Fix will be removing that line of code but is there a particular functionality needed after xd?

2) run the below in the local build of reflex-codebase and it throws the below

    _clist = [title, *[eval(c) for c in d.metadata["components"]]]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eliasderby/Desktop/python/oss/reflex-web/reflex-web/pcweb/pages/docs/__init__.py", line 87, in <listcomp>
    clist = [title, *[eval(c) for c in d.metadata["components"]]]
                      ^^^^^^^
  File "<string>", line 1, in <module>
  File "/home/eliasderby/Desktop/python/oss/reflex-codebase/reflex-codebase/reflex/__init__.py", line 354, in __getattr__
    raise AttributeError(f"module 'reflex' has no attribute {name}") from None
**AttributeError: module 'reflex' has no attribute reflex.lucide**_

3)   run this in venv with requirements installed but throws the below
    _clist = [title, *[eval(c) for c in d.metadata["components"]]]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eliasderby/Desktop/python/oss/reflex-web/reflex-web/pcweb/pages/docs/__init__.py", line 87, in <listcomp>
    clist = [title, *[eval(c) for c in d.metadata["components"]]]
                      ^^^^^^^
  File "<string>", line 1, in <module>
**AttributeError: module 'reflex.components.radix.themes' has no attribute 'Callout'. Did you mean: 'callout'?**_

**Comment by picklelo** [comment]
Reflex-web requires the `main` branch of reflex to run. You can either try to checkout `reflex` and install that latest version rather than through pip. Or try to go back a few days in the commits and check if it runs. In the future we will probably move this into the same repo as `reflex` so that these compatibility issues don't happen.

**Comment by Yummy-Yums** [comment]
followed through with this and it works now, but got some next js hydration errors popping up
![image](https://github.com/reflex-dev/reflex-web/assets/77977520/cfa167a8-eb7f-4313-8814-5bc1dc593e57)

**Comment by picklelo** [comment]
I published a prerelease 0.3.10a1 - can you try running with that?
