### ISSUE TITLE
[REF-2584] rx.download here link redirects to 404 page.

### ISSUE THREAD

**Issue by murdak** [reflex-dev/reflex-web#423]
From https://reflex.dev/docs/components/assets/

Under With rx.download event section.

The link in Reference page for rx.download[ here ](https://reflex.dev/docs/api-reference/**special-events**).

Wrong link: https://reflex.dev/docs/api-reference/special-events

Correct link: https://reflex.dev/docs/api-reference/special_events/

<sub>[REF-2584](https://linear.app/reflex-dev/issue/REF-2584/rxdownlnoad-here-link-redirects-to-404-page)</sub>

**Comment by picklelo** [comment]
Thanks for raising this, will fix
