### ISSUE TITLE
Improve search functionality on smaller screen size

### ISSUE THREAD

**Issue by masenf** [reflex-dev/reflex-web#52]
The pynecone docs search box is part of the main navbar... however it is only rendered on screen sizes > 48em width (for me that's full screen on M1 Mac Book Pro). There is no other indication on smaller screens that search functionality exists.

There needs to be an alternative way to access search from phones and tablets.

**Comment by masenf** [comment]
Currently the easiest way to search the docs is via github against this repo...

**Comment by FHU-yezi** [comment]
> It's particularly hard to find pynecone documentation on existing search engines (almost every query links to announcements and blogs about the release).
> 
> Further there doesn't appear to be a search function on the pynecone.io site itself that allows searching the docs, which would really improve discoverability.

We currently have a scearch bar in desktop website, but not for the mobile.

**Comment by masenf** [comment]
Ah okay, I do see that now. Although I'm using a "desktop" browser for development, the 48em break for displaying the search bar at all seems a bit big. If the search bar isn't visible, there's no indication anywhere else in the app that search even exists.

Since the search box itself is kind of just a fancy button and the real search functionality is implemented in the modal, i think I could make sense to just use a magnifying glass icon on the right that pops open the centered modal when tapped. This would work for small-browser-window users like myself, as well as the hordes of people thumbing through the docs on their phone from a blog or post.

# How it is now

https://user-images.githubusercontent.com/1524005/232276800-65c8f95f-b11b-4b9d-a9d7-bbc886872536.mov

# What I'd like to see

![image](https://user-images.githubusercontent.com/1524005/232277293-2faf9fd7-49a5-4e73-81f0-292af2705347.png)


Currently I'm still feeling my way around the docs and trying to figure out how easy this would be to achieve. Wasn't successful in a 15 minute romp, so will have to put some concerted effort in down the road.

**Comment by picklelo** [comment]
search is available now
