### ISSUE TITLE
Cannot run the website locally

### ISSUE THREAD

**Issue by Fanisting** [reflex-dev/reflex-web#57]
I git clone the project to my local folder, and I run `pc init` and `pc run`, but got unexpected error:
`AttributeError: module 'pynecone' has no attribute 'memo'`

**Comment by ElijahAhianyo** [comment]
I think you should update your pynecone version to the latest(v0.1.24)

**Comment by Fanisting** [comment]
> 

Hi, thanks for your response! I get to know the error I mentioned is contradiction about the versions of packages `httpx` and `httpcore`. However, I got the same error in a former issue:

```
AssertionError: Expected comment, got class Text(ChakraComponent):
    """Render a paragraph of text."""
    tag = "Text"
    # Override the tag. The default tag is `<p>`.
    as_: Var[str]
```

Can you kindly help me to figure it out why?

**Comment by ElijahAhianyo** [comment]
mm. From this error, it looks like you use windows. The inspect library doesnt seem to use the `linesep` of the respective os( it uses `\n` irrespective of the host os). In windows, its `\r\n` as opposed to `\n` in unix destros.  If you change this line in https://github.com/pynecone-io/pcweb/blob/28d8b35ccc097147d7470ed50e3524e714798df8/pcweb/pages/docs/component.py#L47
to
```python
for line in inspect.getsource(self.component).split("\n")
``` 
It should work

**Comment by kylekinnaman** [comment]
I'm getting different errors on `pc run` under version 0.1.29 (Debian 11 Bullseye):

```
Traceback (most recent call last):
  File "/usr/local/bin/pc", line 8, in <module>
    sys.exit(main())
  File "/home/kk/.local/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/kk/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/kk/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/kk/.local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kk/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kk/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/kk/.local/lib/python3.9/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/kk/.local/lib/python3.9/site-packages/pynecone/pc.py", line 115, in run
    app = prerequisites.get_app()
  File "/home/kk/.local/lib/python3.9/site-packages/pynecone/utils/prerequisites.py", line 102, in get_app
    return __import__(module, fromlist=(constants.APP_VAR,))
  File "/home/kk/dev/pcweb/pcweb/pcweb.py", line 9, in <module>
    from pcweb.pages import routes
  File "/home/kk/dev/pcweb/pcweb/pages/__init__.py", line 1, in <module>
    from pcweb.route import Route
  File "/home/kk/dev/pcweb/pcweb/route.py", line 10, in <module>
    class Route(Base):
  File "/home/kk/dev/pcweb/pcweb/route.py", line 17, in Route
    title: str | None = None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

I started commenting out the pipe but that led to more issues and obviously will break things.

**Comment by ElijahAhianyo** [comment]
You need python version>=3.10 to run pcweb locally

**Comment by ElijahAhianyo** [comment]
> I'm getting different errors on `pc run` under version 0.1.29 (Debian 11 Bullseye):
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/bin/pc", line 8, in <module>
>     sys.exit(main())
>   File "/home/kk/.local/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
>     return get_command(self)(*args, **kwargs)
>   File "/home/kk/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/kk/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "/home/kk/.local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/kk/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/kk/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "/home/kk/.local/lib/python3.9/site-packages/typer/main.py", line 532, in wrapper
>     return callback(**use_params)  # type: ignore
>   File "/home/kk/.local/lib/python3.9/site-packages/pynecone/pc.py", line 115, in run
>     app = prerequisites.get_app()
>   File "/home/kk/.local/lib/python3.9/site-packages/pynecone/utils/prerequisites.py", line 102, in get_app
>     return __import__(module, fromlist=(constants.APP_VAR,))
>   File "/home/kk/dev/pcweb/pcweb/pcweb.py", line 9, in <module>
>     from pcweb.pages import routes
>   File "/home/kk/dev/pcweb/pcweb/pages/__init__.py", line 1, in <module>
>     from pcweb.route import Route
>   File "/home/kk/dev/pcweb/pcweb/route.py", line 10, in <module>
>     class Route(Base):
>   File "/home/kk/dev/pcweb/pcweb/route.py", line 17, in Route
>     title: str | None = None
> TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
> ```
> 
> I started commenting out the pipe but that led to more issues and obviously will break things. 

You need python version>=3.10 to run pcweb locally
