### ISSUE TITLE
[REF-2582] Feature Request: Add Dark Mode to Documentation Page

### ISSUE THREAD

**Issue by moistwrist3** [reflex-dev/reflex-web#597]
Our documentation page lacks a dark mode feature, which can be inconvenient for users who prefer dark themes or work in low-light environments. Adding a dark mode option would enhance the accessibility and user experience of our documentation, allowing users to comfortably browse and read content without straining their eyes.

Implementation Suggestions:

    Integrate a toggle switch or settings option on the documentation page to allow users to switch between light and dark modes.

    Ensure that text, images, and other elements are optimized for visibility and readability in both light and dark modes.

<sub>[REF-2582](https://linear.app/reflex-dev/issue/REF-2582/feature-request-add-dark-mode-to-documentation-page)</sub>

**Comment by moistwrist3** [comment]
https://reflex.dev/docs/getting-started/introduction/

**Comment by Alek99** [comment]
![Screenshot 2024-04-07 at 10 35 40 PM](https://github.com/reflex-dev/reflex-web/assets/38776361/b4d53664-fed9-4e69-a85e-542c603970b7)

Coming very soon

**Comment by Alek99** [comment]
New website and doc design shipping this week
