### ISSUE TITLE
Issue with reflex.dev documentation

### ISSUE THREAD

**Issue by Xtreemrus** [reflex-dev/reflex-web#739]
Path: /docs/authentication/authentication-overview

Link: https://github.com/dentro-innovation/reflex_template/blob/main/reflex_template/utils/clerk_wrapper.py -> 404 - page not found

**Comment by picklelo** [comment]
Looks like clerk has been moved to it's own Github: https://github.com/kroo/reflex-clerk

We will update the docs.

**Comment by picklelo** [comment]
Fixes are merged, website will be updated soon.
