### ISSUE TITLE
Pillow image type

### ISSUE THREAD

**Issue by abdullahkhalids** [reflex-dev/reflex-web#753]
Path: /docs/library/media/image

The docs currently have an example of loading a Pillow image

```python
class ImageState(rx.State):
    url = f"https://picsum.photos/id/1/200/300"
    image = Image.open(requests.get(url, stream=True).raw)
```

What is the type for image? I want to have no image when user open the page, and later load an image dynamically. So I want

```python
class ImageState(rx.State):
    image: sometype
```

I have tried to put in a variety of different types, such as `PIL.Image` or `PIL.JpegImagePlugin.JpegImageFile`, but I get errors like
```
State vars must be primitive Python types, Plotly figures, Pandas dataframes, or subclasses of rx.Base
```

What is the correct type of Pillow images that reflex accepts?

**Comment by picklelo** [comment]
@abdullahkhalids The type is `PIL.Image.Image`. But currently it doesn't have a default value (this is something we should support).

```python
from PIL import Image

class ImageState(rx.State):
    url = f"https://picsum.photos/id/1/200/300"
    image: Image.Image = Image.new('RGB', (1,1)) # requires an initial value currently
```

You can use this to set it blank initially, and load your image later.

**Comment by abdullahkhalids** [comment]
Thanks.
