### ISSUE TITLE
"Edit this page" button goes to 404

### ISSUE THREAD

**Issue by stock90975** [reflex-dev/reflex-web#840]
On many pages in the docs, eg:
https://reflex.dev/docs/getting-started/installation/

the "Edit this page" button at the bottom of the page goes to 404
https://github.com/reflex-dev/reflex-web/tree/main/docs/getting-started/installation/.md

as what should be:
https://github.com/reflex-dev/reflex-web/blob/main/docs/getting-started/installation.md

**Comment by doshikaran** [comment]
Hi @stock90975,

I saw this issue and have fixed it. I've created a pull request to address the problem with the "Edit this page" button leading to a 404 error. The link now correctly points to the appropriate file location within the GitHub repository.

You can check the PR here: https://github.com/reflex-dev/reflex-web/pull/841

**Comment by ai-naymul** [comment]
@stock90975 Please close this issue if its fixed already

**Comment by stock90975** [comment]
1. I'm not seeing this at https://reflex.dev/docs/getting-started/introduction/, still goes to 404
2. If the fix is to have this not hardcoded (https://github.com/reflex-dev/reflex-web/pull/841/files/7a8eaaca78c7563ed3856596d2bcd8ec0fa7e5cd), how do I see if that is done?
3. As mentioned, this is a problem for many pages. I don't think fixing one page is the solution. The page mentioned was just an example of the problem.
