### ISSUE TITLE
Issue with reflex.dev documentation

### ISSUE THREAD

**Issue by Ohhora** [reflex-dev/reflex-web#907]
Path: /docs/hosting/deploy-quick-start/
i've already deploy my app to gallery, but i would like to remove my app on reflex gallery.
Although i found a way to do this in documentation of reflex, there's no indication about it.
How can i remove or change my app had been submitted???

please, fix it.

**Comment by Alek99** [comment]
If you delete the app and then deploy a new one and don't choose to share it, it will no longer show up.

**Comment by Alek99** [comment]
Removed
